---

    - name: Add the Docker group
      group:
        name=docker
        state=present
      become_method: sudo
      become: yes


#    - name: Add the elasticsearch group gid 9999
#      group:
#        name={{elastic_user}}
#        state=present
#        gid=9999
#      become_method: sudo
#      become: yes


#   - name: Create elasticsearch user
#     user:
#       name={{elastic_user}}
#       uid=9999
#        groups={{elastic_user}},docker
#      become_method: sudo
#      become: yes

#    - name: Set primary group for the elasticsearch user
#      command: usermod -g {{elastic_user}} {{elastic_user}}
#      become_method: sudo
#      become: yes

    - name: Install Docker
      yum:
        name=docker
        state=latest
      become_method: sudo
      become: yes

    - name: Start the Docker daemon
      service:
        name=docker
        state=started
        enabled=yes
      become_method: sudo
      become: yes


    - name: Setting up "/root/elasticsearch/docker"
      file:
        path=/root/{{elastic_user}}/docker
        state=directory
        owner=root
        group=root
      become_method: sudo
      become: yes


    - name: Copying Dockerfile
      copy:
        src=../../../elasticsearch/Dockerfile
        dest=/root/{{elastic_user}}/docker/Dockerfile
        owner=root
        group=root
        mode=0744
      become_method: sudo
      become: yes


    - name: Copying Docker entry point
      copy:
        src=../../../elasticsearch/docker-entrypoint.sh
        dest=/root/{{elastic_user}}/docker/docker-entrypoint.sh
        owner=root
        group=root
        mode=0744
      become_method: sudo
      become: yes

    - name: Copying elasticsearch run script
      copy:
        src=../../../elasticsearch/run-elasticsearch.sh
        dest=/root/{{elastic_user}}/docker/run-elasticsearch.sh
        owner=root
        group=root
        mode=0744
      become_method: sudo
      become: yes
