---
    - name: Running yum upgrade
      yum:
        name=*
        state=latest
      become_method: sudo
      become: yes

    - name: Install wget
      yum:
        name=wget
        state=latest
      become_method: sudo
      become: yes

    - name: Disable SELinux
      selinux:
        state=disabled
      become_method: sudo
      become: yes

