---
    - name: Setting up "/root/{{elastic_user}}/data"
      file:
        path=/root/{{elastic_user}}/data
        state=directory
        owner=root
        group=root
      become_method: sudo
      become: yes



    - name: Setting up "/root/{{elastic_user}}/logs"
      file:
        path=/root/{{elastic_user}}/logs
        state=directory
        owner=root
        group=root
      become_method: sudo
      become: yes

    - name: Setting up "/root/{{elastic_user}}/config"
      file:
        path=/root/{{elastic_user}}/config
        state=directory
        owner=root
        group=root

      become_method: sudo
      become: yes

    - name: Copying "config/elasticsearch.yml"
      copy:
        src=../../../elasticsearch/elastic_config/elasticsearch.yml
        dest=/root/{{elastic_user}}/config/elasticsearch.yml
        owner=root
        group=root
        mode=0744
      become_method: sudo
      become: yes

    - name: Copying "config/logging.yml"
      copy:
        src=../../../elasticsearch/elastic_config/logging.yml
        dest=/root/{{elastic_user}}/config/logging.yml
        owner=root
        group=root
        mode=0744
      become_method: sudo
      become: yes
