---
    - name: Setting up "/home/{{elastic_user}}/data"
      file:
        path=/home/{{elastic_user}}/data
        state=directory
        owner={{elastic_user}}
        group={{elastic_user}}
      become_method: sudo
      become: yes



    - name: Setting up "/home/{{elastic_user}}/logs"
      file:
        path=/home/{{elastic_user}}/logs
        state=directory
        owner={{elastic_user}}
        group={{elastic_user}}
      become_method: sudo
      become: yes

    - name: Setting up "/home/{{elastic_user}}/config"
      file:
        path=/home/{{elastic_user}}/config
        state=directory
        owner={{elastic_user}}
        group={{elastic_user}}

      become_method: sudo
      become: yes

    - name: Copying "config/elasticsearch.yml"
      copy:
        src=../../../elastic_config/elasticsearch.yml
        dest=/home/{{elastic_user}}/config/elasticsearch.yml
        owner={{elastic_user}}
        group={{elastic_user}}
        mode=0744
      become_method: sudo
      become: yes

    - name: Copying "config/logging.yml"
      copy:
        src=../../../elastic_config/logging.yml
        dest=/home/{{elastic_user}}/logs/logging.yml
        owner={{elastic_user}}
        group={{elastic_user}}
        mode=0744
      become_method: sudo
      become: yes
